site_name: Project Calzone Documentation

nav:
  - Home: index.md
  - Calzone Game: 
    - About: "game/index.md"
  - Calzone Web:
    - About: "web/index.md"
    - REST API Quick Reference: "web/REST API Quick Reference.md"
  - About: about.md

theme:
  name: material
