site_name: Project Calzone Documentation

nav:
  - Home: index.md
  - Calzone Game: 
    - Calzone Game: "game/index.md"
    - Building From Source: "game/building-from-source.md"
  - Calzone Web:
    - Calzone Web: "web/index.md"
    - Building From Source: "web/building-from-source.md"
    - REST API Quick Reference: "web/REST API Quick Reference.md"
  - About: about.md

theme:
  name: material
